### ISSUE TITLE
Incorrectly cropped image

### ISSUE THREAD

**Issue by f0enix** [ZhongUncle/SwiftUI_ImageCropper#1]
i just tried the demo on the simulator and it seems that the cropped image does not match exactly what i selected in the cropper ui. I think there is an issue with the crop rect calculation.
![Simulator Screen Shot - iPhone 11 - 2022-11-06 at 11 14 55](https://user-images.githubusercontent.com/72214428/200158960-17d184ac-93eb-4d86-8bfc-c2dc25ca39df.png)
Result
![Simulator Screen Shot - iPhone 11 - 2022-11-06 at 11 15 01](https://user-images.githubusercontent.com/72214428/200158972-275ec6f5-235a-42b2-8ebe-04e6c956dee6.png)

As you can see clearly i cropped to the number grid from 33 to 58 but the cropped image returned 53 to 83 portion which clearly is incorrect. Can you please have a look?

**Comment by ZhongUncle** [comment]
Thanks for usage and reporting this bug.
The cause of this bug is Apple changed the value of UIScreen.main.bounds.height. For example, this value of iPhone 11 Pro is 1125pt, but now is 812pt, I think maybe Apple ignores the bar or something. So the image cropped is below the selected area. I will fix it as soon as possible.

**Comment by ZhongUncle** [comment]
> i just tried the demo on the simulator and it seems that the cropped image does not match exactly what i selected in the cropper ui. I think there is an issue with the crop rect calculation.
> 
> ![Simulator Screen Shot - iPhone 11 - 2022-11-06 at 11 14 55](https://user-images.githubusercontent.com/72214428/200158960-17d184ac-93eb-4d86-8bfc-c2dc25ca39df.png)
> 
> Result
> 
> ![Simulator Screen Shot - iPhone 11 - 2022-11-06 at 11 15 01](https://user-images.githubusercontent.com/72214428/200158972-275ec6f5-235a-42b2-8ebe-04e6c956dee6.png)
> 
> 
> 
> As you can see clearly i cropped to the number grid from 33 to 58 but the cropped image returned 53 to 83 portion which clearly is incorrect. Can you please have a look?
> 
> 

Thanks for usage and reporting this bug.
The cause of this bug is Apple changed the value of UIScreen.main.bounds.height. For example, this value of iPhone 11 Pro is 1125pt, but now is 812pt, I think maybe Apple ignores the bar or something. So the image cropped is below the selected area. I will fix it as soon as possible.

**Comment by f0enix** [comment]
i don't think using the screen size is good way to handle the crop ui. This will likely cause issues if the cropper is presented on an ipad where modal sheets are not full sized or even in split view/slide over mode on ipads. For example if i try to put the demo app in split view mode on ipad simulator, the cropper view is not properly rendered. The image and cropper overlay is out of the screen due to wrong assumption of the width/height.
![Simulator Screen Shot - iPad Pro (9 7-inch) - 2022-11-07 at 10 15 18](https://user-images.githubusercontent.com/72214428/200239139-faad532e-a682-49d3-b9bb-2170ec929131.png)

**Comment by ZhongUncle** [comment]
Please start a new issue? It will help others to get information quickly and directly.
