### ISSUE TITLE
CropperView colors are inverted

### ISSUE THREAD

**Issue by f0enix** [ZhongUncle/SwiftUI_ImageCropper#4]
When i put the system in dark mode, the cropper appears white while the app is correctly in dark mode:
![Simulator Screen Shot - iPad Pro (9 7-inch) - 2022-11-24 at 10 15 57](https://user-images.githubusercontent.com/72214428/203708071-4b79c366-d59c-4bf0-81ff-ebc7e33ac675.png)

![Simulator Screen Shot - iPad Pro (9 7-inch) - 2022-11-24 at 10 11 46](https://user-images.githubusercontent.com/72214428/203707895-fd54409a-91d2-41f3-93cb-67e766d03bd0.png)

Light mode, cropper appears black:
![Simulator Screen Shot - iPad Pro (9 7-inch) - 2022-11-24 at 10 15 40](https://user-images.githubusercontent.com/72214428/203708237-f4101b53-bb3e-43fe-8747-b867256a6d50.png)

![Simulator Screen Shot - iPad Pro (9 7-inch) - 2022-11-24 at 10 12 09](https://user-images.githubusercontent.com/72214428/203707846-bdaea496-f743-4d9a-a6a0-0da9bc2b6090.png)

I believe the colors are the opposite of what it should be. When the system is in dark appearance, the cropper should be dark too.

**Comment by ZhongUncle** [comment]
This bug is because  I just used default and did not set the  .foregroundColor()` of `Rectangle()`. In default, the `.foregroundColor()` of `Rectangle()` is `.black` in light appearance, and is `.white` in dark appearance. 
Thanks for report this bug to make me know SwiftUI change the `.foregroundColor()` in different appearances.

**Comment by ZhongUncle** [comment]
This bug is because  I just used default and did not set the `.foregroundColor()` of `Rectangle()`. In default, the `.foregroundColor()` of `Rectangle()` is `.black` in light appearance, and is `.white` in dark appearance. 
Thanks for report this bug to make me know SwiftUI change the `.foregroundColor()` in different appearances.
